#include <stdbool.h>
#include <stdint.h>

// ---- This header is automatically generated by Atom ----

void atom_tick();

extern struct {  /* example */
  struct {  /* example */
    struct {  /* example */
      struct {  /* checkButton1 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton1;
      struct {  /* checkButton2 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton2;
      struct {  /* checkButton3 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton3;
      struct {  /* checkButton4 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton4;
      struct {  /* checkButton5 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton5;
      struct {  /* checkButton6 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton6;
      struct {  /* checkButton7 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton7;
      struct {  /* checkButton8 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton8;
      struct {  /* checkButton9 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton9;
      struct {  /* checkButton10 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton10;
      struct {  /* checkButton11 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton11;
      struct {  /* checkButton12 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton12;
      struct {  /* checkButton13 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton13;
      struct {  /* checkButton14 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton14;
      struct {  /* checkButton15 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton15;
      struct {  /* checkButton16 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton16;
      struct {  /* measureVoltage */
        bool voltage_trigger;
        uint64_t threshold;
      } measureVoltage;
    } example;
  } example;
} example;


// ---- End automatically-generated header ----
