#include <stdbool.h>
#include <stdint.h>



// ---- This source is automatically generated by Atom ----
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

#define WATCHDOG_PERIOD 15

static uint64_t watchdog_deadline = WATCHDOG_PERIOD;

static uint16_t voltage = 0;

static bool button_port[16] = { false };

void reset_watchdog(void);
void measure_voltage(void);
// End header


static uint64_t __global_clock = 0;






struct {  /* example */
  struct {  /* example */
    struct {  /* example */
      struct {  /* checkButton1 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton1;
      struct {  /* checkButton2 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton2;
      struct {  /* checkButton3 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton3;
      struct {  /* checkButton4 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton4;
      struct {  /* checkButton5 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton5;
      struct {  /* checkButton6 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton6;
      struct {  /* checkButton7 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton7;
      struct {  /* checkButton8 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton8;
      struct {  /* checkButton9 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton9;
      struct {  /* checkButton10 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton10;
      struct {  /* checkButton11 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton11;
      struct {  /* checkButton12 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton12;
      struct {  /* checkButton13 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton13;
      struct {  /* checkButton14 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton14;
      struct {  /* checkButton15 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton15;
      struct {  /* checkButton16 */
        uint8_t timeHeld;
        bool button_pressed;
      } checkButton16;
      struct {  /* measureVoltage */
        bool voltage_trigger;
        uint64_t threshold;
      } measureVoltage;
    } example;
  } example;
} example =
{  /* example */
  {  /* example */
    {  /* example */
      {  /* checkButton1 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton2 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton3 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton4 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton5 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton6 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton7 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton8 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton9 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton10 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton11 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton12 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton13 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton14 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton15 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* checkButton16 */
        /* timeHeld */  0,
        /* button_pressed */  false
      },
      {  /* measureVoltage */
        /* voltage_trigger */  false,
        /* threshold */  0ULL
      }
    }
  }
};

/* example.example.checkButton1.pressed */
static void __r0() {
  bool __0 = true;
  uint8_t __1 = 1;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton1.timeHeld;
  uint8_t __4 = __3 + __1;
  uint8_t __5 = 0;
  uint8_t __6 = __2 ? __4 : __5;
  uint8_t __7 = 50;
  bool __8 = __7 < __3;
  if (__0) {
  }
  example.example.example.checkButton1.timeHeld = __6;
  example.example.example.checkButton1.button_pressed = __8;
}

/* example.example.checkButton2.pressed */
static void __r1() {
  bool __0 = true;
  uint8_t __1 = 2;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton2.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton2.timeHeld = __7;
  example.example.example.checkButton2.button_pressed = __9;
}

/* example.example.checkButton3.pressed */
static void __r2() {
  bool __0 = true;
  uint8_t __1 = 3;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton3.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton3.timeHeld = __7;
  example.example.example.checkButton3.button_pressed = __9;
}

/* example.example.checkButton4.pressed */
static void __r3() {
  bool __0 = true;
  uint8_t __1 = 4;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton4.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton4.timeHeld = __7;
  example.example.example.checkButton4.button_pressed = __9;
}

/* example.example.checkButton5.pressed */
static void __r4() {
  bool __0 = true;
  uint8_t __1 = 5;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton5.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton5.timeHeld = __7;
  example.example.example.checkButton5.button_pressed = __9;
}

/* example.example.checkButton6.pressed */
static void __r5() {
  bool __0 = true;
  uint8_t __1 = 6;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton6.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton6.timeHeld = __7;
  example.example.example.checkButton6.button_pressed = __9;
}

/* example.example.checkButton7.pressed */
static void __r6() {
  bool __0 = true;
  uint8_t __1 = 7;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton7.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton7.timeHeld = __7;
  example.example.example.checkButton7.button_pressed = __9;
}

/* example.example.checkButton8.pressed */
static void __r7() {
  bool __0 = true;
  uint8_t __1 = 8;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton8.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton8.timeHeld = __7;
  example.example.example.checkButton8.button_pressed = __9;
}

/* example.example.checkButton9.pressed */
static void __r8() {
  bool __0 = true;
  uint8_t __1 = 9;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton9.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton9.timeHeld = __7;
  example.example.example.checkButton9.button_pressed = __9;
}

/* example.example.checkButton10.pressed */
static void __r9() {
  bool __0 = true;
  uint8_t __1 = 10;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton10.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton10.timeHeld = __7;
  example.example.example.checkButton10.button_pressed = __9;
}

/* example.example.checkButton11.pressed */
static void __r10() {
  bool __0 = true;
  uint8_t __1 = 11;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton11.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton11.timeHeld = __7;
  example.example.example.checkButton11.button_pressed = __9;
}

/* example.example.checkButton12.pressed */
static void __r11() {
  bool __0 = true;
  uint8_t __1 = 12;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton12.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton12.timeHeld = __7;
  example.example.example.checkButton12.button_pressed = __9;
}

/* example.example.checkButton13.pressed */
static void __r12() {
  bool __0 = true;
  uint8_t __1 = 13;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton13.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton13.timeHeld = __7;
  example.example.example.checkButton13.button_pressed = __9;
}

/* example.example.checkButton14.pressed */
static void __r13() {
  bool __0 = true;
  uint8_t __1 = 14;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton14.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton14.timeHeld = __7;
  example.example.example.checkButton14.button_pressed = __9;
}

/* example.example.checkButton15.pressed */
static void __r14() {
  bool __0 = true;
  uint8_t __1 = 15;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton15.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton15.timeHeld = __7;
  example.example.example.checkButton15.button_pressed = __9;
}

/* example.example.checkButton16.pressed */
static void __r15() {
  bool __0 = true;
  uint8_t __1 = 16;
  bool __2 = button_port[__1];
  uint8_t __3 = example.example.example.checkButton16.timeHeld;
  uint8_t __4 = 1;
  uint8_t __5 = __3 + __4;
  uint8_t __6 = 0;
  uint8_t __7 = __2 ? __5 : __6;
  uint8_t __8 = 50;
  bool __9 = __8 < __3;
  if (__0) {
  }
  example.example.example.checkButton16.timeHeld = __7;
  example.example.example.checkButton16.button_pressed = __9;
}

/* example.example.measureVoltage.measure */
static void __r16() {
  bool __0 = true;
  if (__0) {
    measure_voltage();
  }
}

/* example.example.measureVoltage.read.checkLower */
static void __r17() {
  uint16_t __0 = voltage;
  uint16_t __1 = 18000;
  bool __2 = __0 < __1;
  bool __3 = ! __2;
  bool __4 = example.example.example.measureVoltage.voltage_trigger;
  bool __5 = __3 && __4;
  bool __6 = ! __5;
  bool __7 = __3 && __6;
  bool __8 = ! __7;
  if (__2) {
    printf("Voltage under threshold!\n");
  }
  example.example.example.measureVoltage.voltage_trigger = __8;
}

/* example.example.measureVoltage.read.checkUpper */
static void __r18() {
  bool __0 = example.example.example.measureVoltage.voltage_trigger;
  uint16_t __1 = 20000;
  uint16_t __2 = voltage;
  bool __3 = __1 < __2;
  bool __4 = ! __3;
  bool __5 = __0 && __4;
  bool __6 = __4 && __0;
  uint64_t __7 = __global_clock;
  uint64_t __8 = 10ULL;
  uint64_t __9 = __7 + __8;
  uint64_t __10 = example.example.example.measureVoltage.threshold;
  uint64_t __11 = __6 ? __9 : __10;
  if (__5) {
    printf("Resetting countdown...\n");
  }
  example.example.example.measureVoltage.threshold = __11;
}

/* example.example.measureVoltage.read.checkTimer */
static void __r19() {
  bool __0 = example.example.example.measureVoltage.voltage_trigger;
  uint64_t __1 = __global_clock;
  uint64_t __2 = example.example.example.measureVoltage.threshold;
  bool __3 = __1 < __2;
  bool __4 = ! __3;
  bool __5 = __0 && __4;
  bool __6 = __4 && __0;
  bool __7 = ! __6;
  bool __8 = __7 && __0;
  if (__5) {
    printf("Voltage back to normal.\n");
  }
  example.example.example.measureVoltage.voltage_trigger = __8;
}

/* example.example.measureVoltage.read */
static void __r20() {
  bool __0 = true;
  uint16_t __1 = voltage;
  if (__0) {
    printf("voltage: %i\n", __1);
  }
}

/* example.example.watchdog */
static void __r21() {
  bool __0 = true;
  if (__0) {
    reset_watchdog();
  }
}


static void __assertion_checks() {
}


void atom_tick()
{

  {
    static uint8_t __scheduling_clock = 0;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r0();  /* example.example.checkButton1.pressed */
      __assertion_checks(); __r1();  /* example.example.checkButton2.pressed */
      __assertion_checks(); __r2();  /* example.example.checkButton3.pressed */
      __assertion_checks(); __r3();  /* example.example.checkButton4.pressed */
      __assertion_checks(); __r4();  /* example.example.checkButton5.pressed */
      __assertion_checks(); __r5();  /* example.example.checkButton6.pressed */
      __assertion_checks(); __r6();  /* example.example.checkButton7.pressed */
      __assertion_checks(); __r7();  /* example.example.checkButton8.pressed */
      __assertion_checks(); __r8();  /* example.example.checkButton9.pressed */
      __assertion_checks(); __r9();  /* example.example.checkButton10.pressed */
      __assertion_checks(); __r10();  /* example.example.checkButton11.pressed */
      __assertion_checks(); __r11();  /* example.example.checkButton12.pressed */
      __assertion_checks(); __r12();  /* example.example.checkButton13.pressed */
      __assertion_checks(); __r13();  /* example.example.checkButton14.pressed */
      __assertion_checks(); __r14();  /* example.example.checkButton15.pressed */
      __assertion_checks(); __r15();  /* example.example.checkButton16.pressed */
      __scheduling_clock = 0;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }
  {
    static uint8_t __scheduling_clock = 0;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r16();  /* example.example.measureVoltage.measure */
      __scheduling_clock = 1;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }
  {
    static uint8_t __scheduling_clock = 1;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r17();  /* example.example.measureVoltage.read.checkLower */
      __assertion_checks(); __r18();  /* example.example.measureVoltage.read.checkUpper */
      __assertion_checks(); __r19();  /* example.example.measureVoltage.read.checkTimer */
      __assertion_checks(); __r20();  /* example.example.measureVoltage.read */
      __scheduling_clock = 1;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }
  {
    static uint8_t __scheduling_clock = 0;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r21();  /* example.example.watchdog */
      __scheduling_clock = 9;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }

  __global_clock = __global_clock + 1;

}


// Start footer
int main(void) {
    while (true) {
        printf("__global_clock = %lu\n", __global_clock);

        if (__global_clock > watchdog_deadline) {
             printf("Watchdog expired!\n");
             exit(1);
        }
        atom_tick();
        usleep(500000);
    }
    return 0;
}

void reset_watchdog(void) {
    printf("Watchdog reset\n");
    watchdog_deadline = __global_clock + WATCHDOG_PERIOD;
}

void measure_voltage(void) {
    voltage = (rand() + rand()) / 2;
}

// End footer

